Name: farm-frenzy-russian-roulette
Version: 1.0
Release: 3
# Tarball generated from installing the game available at the download
# URL by running
# WINEPREFIX=/usr/lib/games/Fram-Frenzy-Russian-Roulette wine russianroulette_setup_full.exe
# cd /usr/lib/games/Farm-Frenzy-Russian-Roulette
# remove-unnecessary-wine-bits
# cd ..
# tar cJf farm-frenzy-russian-roulette.tar.xz Farm-Frenzy-Russian-Roulette
Source0: farm-frenzy-russian-roulette.tar.xz
# Tarball generated by running
# (after installing the game with wine as described above)
Source1: farm-frenzy-russian-roulette-icons.tar.xz
Source2: winegame.c
# Used for creating source tarball, see above
Source3: remove-unnecessary-wine-bits
Summary: Farming game
URL: https://www.myplaycity.com/russian_roulette/
License: Distributable
Group: Games/Arcade
ExclusiveArch: %{ix86} x86_64
%ifarch %{ix86}
Requires: wine
%else
Requires: wine32
# We need the 32bit version of ALSA's pulseaudio plugin
Requires: libalsa-plugins-pulseaudio
%endif

%description
Help the poor astronauts who have to eat genetically modified food in the
colorful game Farm Frenzy 3: Russian Roulette!

In an airport café Scarlett meets her friend whose husband is an astronaut.
Scarlet learns that he has to eat genetically modified food since it is
cheaper to produce! The supplier of these products is the boss' cousin and
he wins the bid every year!

But Scarlett is determined to solve this corrupted case! Help her in the
exciting game Farm Frenzy 3: Russian Roulette! In this time management
game you will breed animals, grow crops, produce cakes and what not!

First you will have just several geese at your disposal.
Don't forget to grow grass and feed the birds so that they won't die of
hunger!

Buy an Egg Powder Plant and produce egg powder. After you build a Cookie
Bakery you will be able to process the egg powder into cookies!

From time to time the bears will appear in your farm. They can destroy
the products and buildings, throw animals off the farm. Catch them in a
cage until they demolish everything!

You can drive to the town by motorcycle and sell all the products and
caught bears! For the achievements in the game you will get fantastic
awards! You will be awarded with beautiful statuettes for such
achievements as having 50 animals on your farm, selling 100 bears or
launching your first rocket.

Become the real hero by saving the astronauts in the game
Farm Frenzy 3: Russian Roulette!

%install
mkdir -p %{buildroot}%{_prefix}/lib/games
cd %{buildroot}%{_prefix}/lib/games
tar xf %{SOURCE0}

mkdir -p %{buildroot}%{_datadir}/icons/hicolor
cd %{buildroot}%{_datadir}/icons/hicolor
tar xf %{SOURCE1}

mkdir -p %{buildroot}%{_bindir}
%__cc %{optflags} -DGAMEPATH=\"%{_prefix}/lib/games/Farm-Frenzy-Russian-Roulette/dosdevices/c:/Program\ Files/MyPlayCity.com/Farm\ Frenzy\ 3\ -\ Russian\ Roulette\" -o %{buildroot}%{_bindir}/%{name} %{SOURCE2}

mkdir -p %{buildroot}%{_datadir}/applications
cat >%{buildroot}%{_datadir}/applications/%{name}.desktop <<'EOF'
[Desktop Entry]
Name=Farm Frenzy
Description=Farming Game
Exec=%{_bindir}/%{name}
Type=Application
StartupNotify=true
Icon=4D13_game_icon.0
EOF

%files
%attr(6755,root,root) %{_bindir}/%{name}
%dir %{_prefix}/lib/games/Farm-Frenzy-Russian-Roulette
%attr(0664,root,games) %{_prefix}/lib/games/Farm-Frenzy-Russian-Roulette/*.reg
%{_prefix}/lib/games/Farm-Frenzy-Russian-Roulette/drive_c
%{_prefix}/lib/games/Farm-Frenzy-Russian-Roulette/dosdevices
%{_prefix}/lib/games/Farm-Frenzy-Russian-Roulette/.update-timestamp
%{_datadir}/applications/*.desktop
%{_datadir}/icons/hicolor/*/*/*
